### ISSUE TITLE
BabelLinks: Sort order of context/languages not definable in output

### ISSUE THREAD

**Issue by achterbahn** [Jako/LangRouter#36] opened 2024-09-05 13:29 UTC
There is no way to define the sort order of the languages shown.

BabelLinks with option "showCurrent".

Example: 
- 3 contexts with 3 languages (de (web), en, fr). Sort order of contexts in manager is defined by "rank" as 
  - de (web)
  - en
  - fr
 
- Output order of languages in frontend by `BabelLinks`: en, fr, de (web)):
  - en
  - fr
  - de (web)

It seems that the sort order is alphabetically by context_key.

Suggest that there should be a way to choose the sort order.

**Comment by Jako** [comment] 2024-09-05 15:29
This is not the Babel repository and the issue looks like a duplicate of https://github.com/mikrobi/babel/issues/215

**Closed as completed by Jako** 2024-09-05 15:29 UTC
